name: Publish Docker Images
on:
  release:
    types: [published]
jobs:
  Publish-Default-Docker-Image:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
      options: --user root
      env:
        GCR_CREDENTIALS_JSON: ${{ secrets.GCR_JSON_KEY }}
        GCLOUD_SERVICE_KEY: ${{ secrets.GCR_JSON_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ~/gcloud-service-key.json
    steps:
    - name: Get Release Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
    - run: |
        echo ${GCR_CREDENTIALS_JSON}  > ~/gcloud-service-key.json
        echo ${GCR_CREDENTIALS_JSON}
        cat ~/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=~/gcloud-service-key.json
        docker version
        gcloud config set project ${GCLOUD_PROJECT_NAME}
        gcloud auth configure-docker --quiet
        docker build . -t gcr.io/${{secrets.GOOGLE_PROJECT_NAME}}/default -f default/Dockerfile
        docker tag gcr.io/${GOOGLE_PROJECT_NAME}/default gcr.io/${DOCKER_IMAGE_NAME}/default:${{ env.RELEASE_VERSION }}
        docker push gcr.io/${GOOGLE_PROJECT_NAME}/default