name: Publish Docker Images
on:
  release:
    types: [published]
jobs:
  Publish-Default-Docker-Image:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
      options: --user root
      env:
        GOOGLE_SERVICE_ACCOUNT_ENCODED: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ENCODED }}
        GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Get Release Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
    - run: |
        echo ${GOOGLE_SERVICE_ACCOUNT_ENCODED} | base64 --decode --ignore-garbage > /gcloud-service-key.json
        gcloud auth activate-service-account --key-file=/gcloud-service-key.json
        gcloud config list
        gcloud config set project ${{ secrets.GOOGLE_PROJECT_NAME }}
        gcloud auth configure-docker --quiet
        pwd
        ls -a
        docker build . -t gcr.io/${{secrets.GOOGLE_PROJECT_NAME}}/default -f default/Dockerfile
        docker tag gcr.io/${GOOGLE_PROJECT_NAME}/default gcr.io/${DOCKER_IMAGE_NAME}/default:${{ env.RELEASE_VERSION }}
        docker push gcr.io/${GOOGLE_PROJECT_NAME}/default