name: Publish Docker Images
on:
  release:
    types: [published]
jobs:
  Default-Service-Unit-Tests:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
      options: --user root
      env:
        GCR_CREDENTIALS_JSON: ${{ secrets.GCR_CREDENTIALS_JSON }}
    steps:
    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/\/refs\/tags\//, '');
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x
        echo $GCR_CREDENTIALS_JSON | gcloud auth activate-service-account --key-file=-
        gcloud config set project ${GCLOUD_PROJECT_NAME}
        gcloud auth configure-docker --quiet
        docker build . -t gcr.io/${{secrets.GOOGLE_PROJECT_NAME}}/default -f default/Dockerfile
        docker tag gcr.io/${DOCKER_IMAGE_NAME}/default gcr.io/${DOCKER_IMAGE_NAME}/default:${{ steps.tag.outputs.result }}
        docker push gcr.io/${DOCKER_IMAGE_NAME}/default