name: Diffgram Testing Workflow
on: [push]
jobs:
  Default-Service-Unit-Tests:
    runs-on: ubuntu-latest
    container:
      image: circleci/python:3.7
      options: --user root
      env:
        NODE_ENV: development
        DATABASE_URL: postgresql+psycopg2://root@localhost/diffgram_unit_tests?sslmode=disable
        RUNNER_ALLOW_RUNASROOT: 1
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: